# Site settings
title: Softega1
description: Tienda de equipo de cómputo y accesorios2
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Softega
user_description: Equipo de cómputo y accesorios4
user_title: Equipo de cómputo y accesorios 5
email: anon@anon.com
twitter_username: 
github_username:  
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
